{{- if .Values.pgadmin4.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: database-pgadmin4
  namespace: {{ .Release.Namespace }}
spec:
  rules:
    - host: {{ get (first .Values.pgadmin4.ingress.hosts) "host" }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: database-pgadmin4
                port:
                  number: 80
{{- end }}
